# Site settings
title: "Jason Willems"
name: "Jason"
description: "Jason Willems – Building products, exploring the world, sharing what I learn"
author: Jason Willems
email: hello@jasonwillems.com

# URL settings
url: "https://jasonwillems.com"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Pagination for blog
paginate: 8
paginate_path: "/blog/page:num/"

# Collections for content types
collections:
  talks:
    output: true
    permalink: /talks/:path/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Google Analytics
# Replace this with your actual GA4 Measurement ID when ready
google_analytics: "G-Q5N6H3PVG2"

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
